---
title: "RNA silencing safeguards plant fertility during viral infection and decreases Turnip rosette virus vertical transmission"
author: "Aimer Gutiérrez-Díaz, Sanjana Holla, Inês Moura and Anders Hafrén"
output: github_document
bibliography: References.bib
link-citations: true
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/biomed-central.csl
---

# Comparative viral transcriptomic analysis

RNA-seq expression data for uninfected and infected Arabidopsis thaliana were obtained from NCBI Bioprojects: TuMV PRJNA788379 @gyula2022ecotype,  TuYV and CaMV PRJEB49403 @chesnais2022comparative,  TyMV PRJNA1103879 @clavel2024metabolic, TCV PRJNA336058 @wu2016analyses, CMV PRJNA1124548 @liu2025mutually and ArLV1 PRJNA863409 @jiang2024deciphering. Read processing, alignment, and gene-level quantification was addressed by mapping with HISAT2 v2.2.1 (Kim et al., 2019) to TAIR10 reference genome and quantifying with featureCounts (Liao et al., 2014). Differential expression was computed separately within each using DESeq2 DEGs were calculated using Deseq2 (Love et al., 2014).

# Viral RdRps structural prediction and phylogenetics

Protein sequences corresponding to CMV 2a, TRV 134K, TyMV 206K, TRoV P2ab, ALV1 P1, TuMV NIb, and PLrV, TuYV, RYMV, AhPV1, TMV, YoMV, TCV, P1AMV RdRps were curated prior to structure prediction. For viruses where the replication protein is polyprotein-derived (e.g., TRoV P2ab), sequences were processed to extract the annotated mature peptide corresponding to the RdRP-containing product, final sequences are available in this repository. Each curated protein was then folded using AlphaFold2 (Jumper et al., 2021), while CaMV P5 PBD was the only RdRp experimentally elucidated (PDB: 8R0S) (Prabaharan et al., 2024). To build a structure-based phylogeny, an initial structural reconstruction was performed using the predicted RdRP models, and a non-LTR retrotransposon reverse transcriptase structure (PDB: 8GH6) was included as an outgroup, in a similar way to Wolf et al. (2018). Finally, a consensus topology was obtained by performing an agreement analysis between trees generated from DALI (Holm, 2022) and Foldtree (Moi et al., 2025) outputs, retaining and scoring clades supported by both approaches.

# References